path: /home/c/dev/ai/datasets/open-images-bees/data # dataset root dir (absolute path -- this will not be the same for you so change it!)
train: images/train # Train Images (relative to 'path')
val: images/validation # Val images (relative to 'path')

# Classes
names: 
    0: bee